id = "alabaster-official"
name = "Alabaster"
version = "0.1.0"
schema_version = 1
authors = ["Nikita Prokopov <niki@tonsky.me>"]
description = "Minimal mindful highlighting"
repository = "https://github.com/tonsky/zed-theme-alabaster"